name: Pizza-App-Deployment

on:
  push:
    branches: [ "main" ]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true  # Node 20 warning hatane ke liye

jobs:
  devops-pipeline:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Modern SonarQube Scan (Exit Code 3 Bypass ke saath)
    - name: SonarQube Scan
      uses: sonarsource/sonarqube-scan-action@v4
      continue-on-error: true  # <--- Isse Exit Code 3 pipeline ko nahi rokega
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: https://sonarcloud.io

    - name: Run Trivy Scan
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        format: 'table'
        severity: 'CRITICAL,HIGH'

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push
      run: |
        docker build -t shm235/pizza-app:latest .
        docker push shm235/pizza-app:latest

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1

    - name: Update Kubeconfig
      run: aws eks update-kubeconfig --name my-eks-cluster

    - name: Apply Manifests
      run: kubectl apply -f k8s/