apiVersion: apps/v1
kind: Deployment
metadata:
  name: pizza-app-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pizza-app
  template:
    metadata:
      labels:
        app: pizza-app
    spec:
      securityContext:      # --- GLOBAL SECURITY ---
        runAsNonRoot: true
        runAsUser: 1000
      containers:
      - name: pizza-container
        image: shm235/pizza-app:latest
        ports:
        - containerPort: 80
        securityContext:    # --- CONTAINER LEVEL SECURITY ---
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"