apiVersion: v1
kind: Service
metadata:
  name: pizza-service
spec:
  type: LoadBalancer # AWS apne aap ek Public DNS/IP dega
  selector:
    app: pizza-app   # Ye wahi naam hai jo deployment mein 'labels' mein tha
  ports:
    - protocol: TCP
      port: 80       # Bahar se log is port par aayenge
      targetPort: 80 # Ye traffic container ke port 80 par jayega